stages:
  - deploy

deploy:
  stage: deploy
  image: google/cloud-sdk:slim
  script:
    - gcloud auth activate-service-account --key-file $GOOGLE_SERVICE_ACCOUNT_FILE
    - gcloud config set project $GOOGLE_PROJECT_ID 
    - gcloud builds submit . --config=cloudbuild.yaml
  only:
    - main
