stages:
  - deploy

deploy_function:
  image: google/cloud-sdk:slim
  stage: deploy
  script:
    - gcloud auth activate-service-account --key-file $GOOGLE_SERVICE_ACCOUNT_FILE
    - gcloud config set project $GOOGLE_PROJECT_ID 
    - gcloud functions deploy gcp-cf-usa-king-intacct --entry-point main --runtime python38 --trigger-topic usa-king-intacct
  only:
    - master
