name: run
on:
  push:
    branches:
      - main
      - develop
      - qa

jobs:
  define-environment:
    name: define-environment
    runs-on: ubuntu-latest
    outputs:
      current_env: ${{ steps.set-env.outputs.THE_ENV }}
    steps:
      - name: set-env
        id: set-env
        run: |
          if [[ $GITHUB_REF == "refs/heads/main" ]]; then
            echo "THE_ENV=PRO"  >> $GITHUB_OUTPUT
          elif [[ $GITHUB_REF == "refs/heads/develop" ]]; then
            echo "THE_ENV=DEV"  >> $GITHUB_OUTPUT
          elif [[ $GITHUB_REF == "refs/heads/qa" ]]; then
            echo "THE_ENV=QA"  >> $GITHUB_OUTPUT
          elif [[ $GITHUB_REF == "refs/heads/stage" ]]; then
            echo "THE_ENV=STG"  >> $GITHUB_OUTPUT
          else
            echo "Unknown branch: $GITHUB_REF"
            exit 1
          fi
      - name: print-branch
        run: |
          branch_name="${GITHUB_REF#refs/heads/}"
          echo "Pushed branch: $branch_name"
  deploy:  
    permissions:
      contents: "read"
      id-token: "write"
    name: "deploy"
    runs-on: ubuntu-latest
    needs: define-environment
    environment: ${{needs.define-environment.outputs.current_env}}
    env:
      THE_ENV: ${{needs.define-environment.outputs.current_env}}
      GOOGLE_PROJECT_ID: ${{ vars.GOOGLE_PROJECT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: ${{ secrets[format('WORKLOAD_IDENTITY_PROVIDER_{0}', env.THE_ENV)] }}
          service_account: ${{ secrets[format('SERVICE_ACCOUNT_{0}', env.THE_ENV)] }} 

      - name: Deploy Cloud Run
        run: |
          echo '${{ vars.GOOGLE_SERVICE_ACCOUNT_JSON }}' >> key.json
          gcloud auth activate-service-account --key-file=key.json
          gcloud config set project ${{ env.GOOGLE_PROJECT_ID }}
          gcloud builds submit . --config=cloudbuild.yaml
