name: Deploy to Cloud Run

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '343.0.0'
          project_id: ${{ vars.GOOGLE_PROJECT_ID }}
          service_account_key: ${{ vars.GOOGLE_SERVICE_ACCOUNT_FILE }}

      - name: Deploy Cloud Run
        run: |
          gcloud builds submit . --config=cloudbuild.yaml


